FROM node:18-alpine
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy source
COPY . .

# Expose dev server
EXPOSE 4200

# Command to run Angular in dev mode
CMD ["npm", "run", "start"]