apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-goals-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: run-goals-backend
  template:
    metadata:
      labels:
        app: run-goals-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/craeyefish/run-goals-backend:latest
          ports:
            - containerPort: 8080
          env:
            # Postgres details
            - name: DB_HOST
              value: "run-goals-db" # matches the DB Service name
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "run_goals"
            # Strava secrets
            - name: STRAVA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: strava-credentials
                  key: STRAVA_CLIENT_ID
            - name: STRAVA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strava-credentials
                  key: STRAVA_CLIENT_SECRET
