apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-goals-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: run-goals-backend
  template:
    metadata:
      labels:
        app: run-goals-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/craeyefish/run-goals-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: STRAVA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: strava-credentials
                  key: STRAVA_CLIENT_ID
            - name: STRAVA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strava-credentials
                  key: STRAVA_CLIENT_SECRET
