apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: run-goals-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: # <-- If you have a default storage class, you can omit this line
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-goals-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: run-goals-db
  template:
    metadata:
      labels:
        app: run-goals-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "run_goals"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: dbdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: dbdata
          persistentVolumeClaim:
            claimName: run-goals-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: run-goals-db
spec:
  selector:
    app: run-goals-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
