apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: run-goals-backend-images
  namespace: flux-system
spec:
  interval: 1m
  image: ghcr.io/craeyefish/run-goals-backend
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: run-goals-backend-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: run-goals-backend-images
  policy:
    semver:
      range: "*"
