apiVersion: batch/v1
kind: CronJob
metadata:
  name: flannel-lease-gc
  namespace: kube-system
spec:
  schedule: '*/15 * * * *' # every 15 min
  jobTemplate:
    spec:
      template:
        spec:
          hostPID: true # enter host namespace
          containers:
            - name: cleaner
              image: busybox:1.36
              securityContext:
                privileged: true # needed to send SIGHUP
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  echo "[lease-gc] removing stale leases"
                  for f in /var/lib/cni/networks/flannel/*; do
                    [ -f "$f" ] || continue
                    ip=$(basename "$f")
                    # if no container has that IP, delete the file
                    if ! nsenter -t 1 -n ip addr show | grep -q " $ip/"; then
                      rm -f "$f"
                      echo "  freed $ip"
                    fi
                  done
                  # tell flannel to reload its lease file list
                  pkill -SIGHUP -f 'flanneld'
              volumeMounts:
                - name: cnidir
                  mountPath: /var/lib/cni/networks
                - name: hostns
                  mountPath: /host
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: cnidir
              hostPath:
                path: /var/lib/cni/networks
            - name: hostns
              hostPath:
                path: /
