# ------------------------------------------------------------------
# 1) Registry – just the repo (no tag)
# ------------------------------------------------------------------
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: run-goals-frontend
  namespace: flux-system
spec:
  image: ghcr.io/craeyefish/run-goals-frontend
  interval: 1m

---
# ------------------------------------------------------------------
# 2) Policy – pick the highest SemVer tag
# ------------------------------------------------------------------
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: run-goals-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: run-goals-frontend
  filterTags:
    pattern: '^frontend-v(?P<v>[0-9]+\.[0-9]+\.[0-9]+.*)$'
    extract: '$v'
  policy:
    semver:
      range: '>=0.0.0'

---
# ------------------------------------------------------------------
# 3) Automation – write the selected digest back to Git
# ------------------------------------------------------------------
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: run-goals-frontend
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: Flux Image Automation
        email: flux@craeyebytes.com
    push:
      branch: main
  update:
    path: ./k8s
    strategy: Setters
