name: Build and Push Backend

on:
  push:
    paths:
      - "backend/**"
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # 1) Set up QEMU for cross-building
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm, arm64

      # 2) Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3) Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # Use GitHub's built-in token for authentication
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4) Build and push multi-arch image
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          # Adjust for your Dockerfile location if not in the root
          file: backend/Dockerfile
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          push: true
          # The tags you want to use. E.g. latest + commit SHA
          tags: |
            ghcr.io/${{ github.repository_owner }}/run-goals-backend:latest
            ghcr.io/${{ github.repository_owner }}/run-goals-backend:${{ github.sha }}
