name: Release Backend

# Manual trigger (button or CLI).  You pick which part to bump.
on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'SemVer part to increment'
        type: choice
        default: patch
        options: [patch, minor, major]

permissions:
  contents: write
  packages: write

jobs:
  bump-tag-build-push:
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------
      # 1) Checkout *all* tags so we can read the latest
      # ------------------------------------------------------------
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ------------------------------------------------------------
      # 2) Determine next tag
      # ------------------------------------------------------------
      - id: next
        name: Compute next version
        shell: bash
        run: |
          # Latest tag matching prefix "backend-v"
          latest=$(git describe --tags --abbrev=0 --match 'backend-v*' 2>/dev/null || echo 'backend-v0.0.0')
          echo "Latest: $latest"

          ver=${latest#backend-v}
          IFS=. read -r major minor patch <<<"$ver"

          case "${{ github.event.inputs.bump }}" in
            major) major=$((major+1)); minor=0; patch=0 ;;
            minor) minor=$((minor+1)); patch=0 ;;
            patch) patch=$((patch+1)) ;;
          esac

          new_tag="backend-v${major}.${minor}.${patch}"
          echo "new_tag=$new_tag" | tee -a "$GITHUB_OUTPUT"
          echo "Releasing $new_tag"

      # ------------------------------------------------------------
      # 3) Create & push the new tag
      # ------------------------------------------------------------
      - name: Create Git tag
        run: |
          git config user.name  "Release Bot"
          git config user.email "release-bot@users.noreply.github.com"
          git tag -a ${{ steps.next.outputs.new_tag }} -m "Release ${{ steps.next.outputs.new_tag }}"
          git push origin ${{ steps.next.outputs.new_tag }}

      # ------------------------------------------------------------
      # 4) Build & push multi-arch image *using that tag*
      # ------------------------------------------------------------
      - uses: docker/setup-qemu-action@v3
        with: { platforms: arm, arm64 }

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: backend/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/run-goals-backend:${{ steps.next.outputs.new_tag }}
            ghcr.io/${{ github.repository_owner }}/run-goals-backend:latest
