name: Release DB
on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'SemVer part to increment'
        type: choice
        default: patch
        options: [patch, minor, major]

permissions:
  contents: write
  packages: write

jobs:
  bump-tag-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # ── 1) compute next tag ─────────────────────────────────────
      - id: next
        shell: bash
        run: |
          latest=$(git describe --tags --abbrev=0 --match 'db-v*' 2>/dev/null || echo 'db-v0.0.0')
          ver=${latest#db-v}; IFS=. read -r MA MI PA <<<"$ver"
          case "${{ github.event.inputs.bump }}" in
            major) MA=$((MA+1)); MI=0; PA=0;;
            minor) MI=$((MI+1)); PA=0;;
            patch) PA=$((PA+1));;
          esac
          echo "tag=db-v$MA.$MI.$PA" | tee -a "$GITHUB_OUTPUT"

      # ── 2) create & push Git tag ────────────────────────────────
      - run: |
          git config user.name  "Release Bot"
          git config user.email "release-bot@noreply.github.com"
          git tag -a ${{ steps.next.outputs.tag }} -m "Release ${{ steps.next.outputs.tag }}"
          git push origin ${{ steps.next.outputs.tag }}

      # ── 3) build multi-arch image and push to GHCR ──────────────
      - uses: docker/setup-qemu-action@v3
        with: { platforms: arm64, arm }
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./database
          file: Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/run-goals-db:${{ steps.next.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/run-goals-db:latest
